# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["mkdavies2@gmail.com"] %>
  email_provider_password: <%= ENV["peiffer331"] %>
  mailchimp_api_key: <%= ENV["0c8316757e9806a45b3c96ea74982ff6-us9"] %>
  mailchimp_list_id: <%= ENV["M8f3a4a408a"] %>
  domain_name: example.com
  owner_email: <%= ENV["mkdavies2@gmail.com"] %>
  secret_key_base: 0d389e9b5a892c897e1f0fc9e8f84e737c2829cf4c9a0ec367455986f6eddb9fb1da94186c50536eec009198164f81d18aa6365ba6994caccf9e6fcb02f31c29

test:
  secret_key_base: b347c35d02855f7ed861cd6f599b93ee04df22147710a3e8ae3e901fe997902b2ea4f287b7a79e2317fee6eb75645bc3aeaa1b6fa99d98d81801e5ba04a6c44f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["mkdavies2@gmail.com"] %>
  email_provider_password: <%= ENV["peiffer331"] %>
  mailchimp_api_key: <%= ENV["0c8316757e9806a45b3c96ea74982ff6-us9"] %>
  mailchimp_list_id: <%= ENV["M8f3a4a408a"] %>
  domain_name: <%= ENV["example.com"] %>
  owner_email: <%= ENV["mkdavies2@gmail.com"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
